spring:
  datasource:
    druid:
      username: xiaotan
      password: 123456
      url: jdbc:mysql://localhost:3306/ssms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&allowPublicKeyRetrieval=true&allowMultiQueries=true
      drive: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.po
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql
logging:
  level:
    com: DEBUG
